#### Importing Modules

In [4]:
import numpy as np

1. Creating Numpy Array:

- 1.1 1D Array

In [7]:
array_1D = [10,15,20]

In [8]:
type(array_1D)

list

In [9]:
numpy_array_1D = np.array(array_1D)

In [10]:
type(numpy_array_1D)

numpy.ndarray

In [38]:
print(array_1D)

[10, 15, 20]


In [37]:
print(numpy_array_1D)

[10 15 20]


In [12]:
var = np.array([6,7,8,9])

In [13]:
type(var)

numpy.ndarray

- 1.2 2D Array

In [15]:
array_2D = [[1,2,3],
            [4,5,6],
            [7,8,9]]

numpy_array_2D = np.array(array_2D)
type(numpy_array_2D)

numpy.ndarray

In [22]:
array_3D = [
            [   [1,3],
                [4,6],
                [7,9] ],

            [   [1,3],
                [4,6],
                [7,9] ],
         ]

numpy_array_3D = np.array(array_3D)
type(numpy_array_3D)

numpy.ndarray

2. Inspecting Numpy Array

In [17]:
numpy_array_1D.shape

(3,)

In [18]:
numpy_array_2D.shape

(3, 3)

In [23]:
numpy_array_3D.shape

(2, 3, 2)

In [24]:
numpy_array_3D.ndim

3

In [25]:
numpy_array_2D.dtype

dtype('int64')

3. Special Numpy Array:

In [35]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
numpy_arange = np.arange(0,20,2)

In [44]:
numpy_arange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
numpy_linspace = np.linspace(0,24,5)
numpy_linspace

array([ 0.,  6., 12., 18., 24.])

4. Indexing

In [49]:
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
X[0]

array([1, 2, 3])

In [ ]:
X[0,1]

np.int64(2)

In [52]:
X[0:2,1] #0:2 > 0,1

array([2, 5])

In [56]:
X[0:2,:] 

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
X[:,:] 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
X[2,:]

array([7, 8, 9])

In [60]:
X = np.array([
    [1,2,3,10],
    [4,5,6,15],
    [7,8,9,20]
])

In [61]:
feature = X[:,0:3]

In [62]:
print(feature)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
